// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_0f3uuVggkN83_cfohNIxWZ_AZuOyo2s',
    appId: '1:325382904467:web:9475e97f0142075cc70b66',
    messagingSenderId: '325382904467',
    projectId: 'medical-assistant-070304',
    authDomain: 'medical-assistant-070304.firebaseapp.com',
    storageBucket: 'medical-assistant-070304.firebasestorage.app',
    measurementId: 'G-01W4ZMN56Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj353OtOVh6TOSlCoaWg9_-pmZwPqCJXs',
    appId: '1:325382904467:android:c8a7f7f14d58ee11c70b66',
    messagingSenderId: '325382904467',
    projectId: 'medical-assistant-070304',
    storageBucket: 'medical-assistant-070304.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQgWRl0P76bW2mSIxhkT-wnLF9Vo4D4KM',
    appId: '1:325382904467:ios:bf6508bb5b747095c70b66',
    messagingSenderId: '325382904467',
    projectId: 'medical-assistant-070304',
    storageBucket: 'medical-assistant-070304.firebasestorage.app',
    iosBundleId: 'com.example.medicalAiAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQgWRl0P76bW2mSIxhkT-wnLF9Vo4D4KM',
    appId: '1:325382904467:ios:bf6508bb5b747095c70b66',
    messagingSenderId: '325382904467',
    projectId: 'medical-assistant-070304',
    storageBucket: 'medical-assistant-070304.firebasestorage.app',
    iosBundleId: 'com.example.medicalAiAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_0f3uuVggkN83_cfohNIxWZ_AZuOyo2s',
    appId: '1:325382904467:web:fb31935ad673ae7ec70b66',
    messagingSenderId: '325382904467',
    projectId: 'medical-assistant-070304',
    authDomain: 'medical-assistant-070304.firebaseapp.com',
    storageBucket: 'medical-assistant-070304.firebasestorage.app',
    measurementId: 'G-XTBDGT8VT4',
  );
}
